---
title: Offline werken
hero_image: images/banner.png
description: standaardinstructies voor offline werken in Scratch
version: 4
listed: false
copyedit: false
last_tested: "2021-03-18"
steps:
  - title: Offline werken
