---
title: ऑफलाइन काम करत आहे
hero_image: प्रतिमा / banner.png
description: Scratch मध्ये ऑफलाइन काम करण्यासाठी मानक सूचना
version: 0
listed: false
copyedit: false
last_tested: "2021-03-18"
steps:
  - 
    title: ऑफलाइन काम करत आहे
