
title: Ukusebenza ngaphandle kweintanethi
hero_image: images/banner.png
description: Imiyalelo esemgangathweni yokusebenza ngaphandle kweintanethi kwiScratch
version: 4
listed: false
copyedit: false
last_tested: "2021-03-18"
steps:
  - title: Ukusebenza ngaphandle kweintanethi
