---
title: Rad izvan mreže
hero_image: images/banner.png
description: Standardne upute za izvanmrežni rad u Scratchu
version: 4
listed: false
copyedit: false
last_tested: "2021-03-18"
steps:
  - title: Rad izvan mreže
