---
title: Gweithio all-lein
hero_image: images/banner.png
description: Cyfarwyddiadau safonol ar gyfer gweithio all-lein yn Scratch
version: 4
listed: false
copyedit: false
last_tested: "2021-03-18"
steps:
  - title: Gweithio all-lein
