---
title: Offline arbeiten
hero_image: images/banner.png
description: Standard Anleitung um offline mit Scratch zu arbeiten
version: 4
listed: false
copyedit: false
last_tested: "2021-03-18"
steps:
  - 
    title: Offline arbeiten
