---
title: Trabalhando offline
hero_image: images/banner.png
description: Instruções padrão para trabalhar offline no Scratch
version: 4
listed: false
copyedit: false
last_tested: "2021-03-18"
steps:
  - 
    title: Trabalhando offline
