---
title: ' Offline Kaam Karna'
hero_image: images/banner.png
description: ' Scratch mein offline kaam karnay kay liye hidayat'
version: 4
listed: false
copyedit: false
last_tested: "2021-03-18"
steps:
  - 
    title: ' Scratch mein offline kaam karnay kay liye hidayat'
