---
title: Treballant fora de línia
hero_image: images/banner.png
description: Instruccions estàndard per treballar fora de línia a Scratch
version: 4
listed: false
copyedit: false
last_tested: "2021-03-18"
steps:
  - title: Treballant fora de línia
