---
title: Práce offline
hero_image: images/banner.png
description: Standardní pokyny pro offline práci ve Scratchi
version: 4
listed: false
copyedit: false
last_tested: "2021-03-18"
steps:
  - 
    title: Práce offline
