---
title: Trabajar sin conexi칩n
hero_image: images/banner.png
description: Instrucciones est치ndar para trabajar sin conexi칩n en Scratch
version: 4
listed: false
copyedit: false
last_tested: "2021-03-18"
steps:
  - title: Trabajar sin conexi칩n
