---
title: Praca w trybie offline
hero_image: images/banner.png
description: Standardowe instrukcje do pracy offline w Scratchu
version: 4
listed: false
copyedit: false
last_tested: "2021-03-18"
steps:
  - title: Praca w trybie offline
