---
title: Arbeta offline
hero_image: images/banner.png
description: Standardinstruktioner för att arbeta offline i Scratch
version: 4
listed: false
copyedit: false
last_tested: "2021-03-18"
steps:
  - 
    title: Arbeta offline
