---
title: Travailler hors ligne
hero_image: images/banner.png
description: instructions standard pour travailler hors ligne dans Scratch
version: 4
listed: false
copyedit: false
last_tested: "2021-03-18"
steps:
  - title: Travailler hors ligne
