---
title: Lavorare offline
hero_image: images/banner.png
description: Istruzioni standard per lavorare offline in Scratch
version: 4
listed: false
copyedit: false
last_tested: "2021-03-18"
steps:
  - 
    title: Lavorare offline
